version: '3'

services:
  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-toor}
      - DOMAIN_NAME=mysql.${BASEHOST:-application.docker}
    command: --innodb-doublewrite=0

  mailcatcher:
    image: mailhog/mailhog
    environment:
      - DOMAIN_NAME=mailcatcher.${BASEHOST:-application.docker}

  application:
    image: dockerwest/php-symfony:${PHPVERSION:-7.1}
    environment:
      - C_UID=${C_UID:-1000}
      - C_GID=${G_UID:-1000}
      - DEVELOPMENT=${DEVELOPMENT:-1}
    volumes:
      - ${APPLICATION:-../application}:/phpapp
    links:
      - mysql
      - mailcatcher

  nginx:
    image: dockerwest/nginx-symfony${SYMFONYVERSION:-4}:${NGINXVERSION:-stable}
    environment:
      - VIRTUAL_HOST=${BASEHOST:-application.docker},${EXTRAHOSTS}
    volumes:
      - ${APPLICATION:-../application}:/phpapp
    links:
      - application
